# Deploy postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.1
          env:
          - name: POSTGRES_PASSWORD
            value: root
          - name: POSTGRES_USER
            value: root
          - name: POSTGRES_DB
            value: movie-review
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
---
# Deploy web application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-review
  template:
    metadata:
      labels:
        app: movie-review
    spec:
      containers:
        - name: movie-review
          image: maycon8609/movie-review:v1
          env:
          - name: ASPNETCORE_HTTP_PORTS
            value: "8080"
          - name: ConnectionStrings__DefaultConnection
            value: "Host=postgre;Database=movie-review;Username=root;Password=root"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: movie-review
spec:
  selector:
    app: movie-review
  ports:
    - port: 80
      targetPort: 8080
      # nodePort: 30000
  type: LoadBalancer